// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rebrouzeklrvcyzvnzve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlYnJvdXpla2xydmN5enZuenZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODM0MzEsImV4cCI6MjA2MzY1OTQzMX0.E-K0MUMNZFqJgEejzPbkcQjXggBI15NG_kK8sTDVDiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);